import { Box, Button, Dialog, DialogContent, DialogTitle, Tab } from '@mui/material';
import { TabContext, TabList, TabPanel } from '@mui/lab';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import { BikeForm } from '../components/bike-form';
import { BikesList } from '../components/bikes-list';
import { BikesReservedByUser } from '../components/bikes-reserved-by-user';
import { Menu } from '../components/menu';
import useBoolean from '../hooks/use-boolean';
import { useCreateBike } from '../hooks/use-create-bike';
import { IBikeFormInputs } from '../models/bike-model';

export enum EnumTab {
  ALL_BIKES = 'all_bikes',
  RESERVED_BIKES = 'reserved_bikes',
};

const Bikes: NextPage = () => {
  const {
    value: isOpen,
    setFalse: handleClose,
    setTrue: handleOpen,
  } = useBoolean(false);
  const { isLoading, mutateAsync, error } = useCreateBike();
  const [tabValue, setTabValue] = useState(EnumTab.ALL_BIKES);

  const handleTabChange = (event: React.SyntheticEvent, newValue: EnumTab) => {
    setTabValue(newValue);
  };

  const onSubmit = async (bike: IBikeFormInputs) => {
    try {
      await mutateAsync(bike);

      handleClose();
    } catch (err) {}
  };

  return (
    <div>
      <Head>
        <title>Bike Rentals - Bikes management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Dialog open={isOpen} onClose={handleClose}>
        <DialogTitle>Add new Bike</DialogTitle>
        <DialogContent>
          <BikeForm
            onSubmit={onSubmit}
            isLoading={isLoading}
            error={error?.message}
          />
        </DialogContent>
      </Dialog>

      <Menu>
        {/* <Box sx={{ marginTop: 2 }}>
          <BikesList />
        </Box> */}
        <Box>
          <TabContext value={tabValue}>
            <Box sx={{ borderBottom: 1, borderColor: 'divider' }}>
              <TabList onChange={handleTabChange} aria-label="User Page Tabs">
                <Tab label="All Bikes" value={EnumTab.ALL_BIKES} />
                <Tab label="Bikes reserved by a user" value={EnumTab.RESERVED_BIKES} />
              </TabList>
            </Box>
            <TabPanel value={EnumTab.ALL_BIKES}>
              <Button variant="contained" onClick={handleOpen} size="large">
                Add new bike
              </Button>
              <Box sx={{ marginTop: 2 }}>
                <BikesList />
              </Box>
            </TabPanel>
            <TabPanel value={EnumTab.RESERVED_BIKES}>
              <BikesReservedByUser />
            </TabPanel>
          </TabContext>
        </Box>
      </Menu>
    </div>
  );
};

export default Bikes;
